<template>
  <div class="flex flex-column w-100">
    <Category v-for="item in news" :key="item.id" :source="item" />
  </div>
</template>

<script setup>
import Category from "./byCategory.vue";
import { useNewsStore } from "../../../stores/index";

const newsStore = useNewsStore();

const news = computed(() => {
  const list = newsStore.getNews();

  const result = [
    {
      id: 0,
      dir: "ltr",
      title: "Politics",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi dolorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi dolorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga ",
      news: list
        .filter((news) => {
          return news.category == "Politics";
        })
        .slice(0, 4),
    },
    {
      id: 1,
      dir: "rtl",
      title: "Economy",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi dolorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi dolorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga ",
      news: list
        .filter((news) => {
          return news.category == "Economy";
        })
        .slice(0, 4),
    },
    {
      id: 2,
      dir: "ltr",
      title: "Society",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi dolorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi dolorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga ",
      news: list
        .filter((news) => {
          return news.category == "Society";
        })
        .slice(0, 4),
    },
    {
      id: 3,
      dir: "rtl",
      title: "Sports",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi dolorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi dolorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga ",
      news: list
        .filter((news) => {
          return news.category == "Sports";
        })
        .slice(0, 4),
    },
    {
      id: 4,
      dir: "ltr",
      title: "Technology",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi dolorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi dolorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga ",
      news: list
        .filter((news) => {
          return news.category == "Technology";
        })
        .slice(0, 4),
    },
    {
      id: 5,
      dir: "rtl",
      title: "International",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi dolorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi dolorem Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga commodi earum sit, ipsum, aliquid facilis debitis atnecessitatibus. Accusamus expedita pariatur deserunt est laborum excepturi doloremLorem ipsum dolor sit amet consectetur adipisicing elit. Id, adipisci nulla aliquam fuga ",
      news: list
        .filter((news) => {
          return news.category == "International";
        })
        .slice(0, 4),
    },
  ];
  return result;
});
</script>
